### ISSUE TITLE
How can I replace the postinst file?

### ISSUE THREAD

**Issue by ronhanson** [astraw/stdeb#100]
Hi,
I've had problems trying to customize the postinst script.

First, after a bdist_deb, I do :

    python3 setup.py --command-packages=stdeb.command bdist_deb --with-python2=True --with-python3=True
    cd deb_dist/<my_package>
    cp /path/my_postinst_script debian/postinst 
    dpkg-buildpackage -rfakeroot -uc -us
    
That creates me 2 .deb files, python-<mypackage>.deb and python3-<mypackage>.deb. (This is quite inefficient but that works).

**The problem is that only the python 2 version of the package contains my own postinst file.**

My questions : 
 - How can I set my custom postinst file for the python3 package?
 - How can I set a custom postinst ?
 - Which programs creates the default postinst file?

Do you think I could patch stdeb to include a custom postinst with a command line argument? If so what would be the best way?

Thanks in advance!

**Comment by p1otr** [comment]
hint: debian/python-foo.postinst, debian/python3-foo.postinst
It's not something stdeb should touch, IMO

**Comment by ronhanson** [comment]
Ok thanks P1otr! It works fine now.
Full working commands :

    python3 setup.py --command-packages=stdeb.command bdist_deb --with-python2=True --with-python3=True
    cd deb_dist/<my_package>
    cp /path/\<my_package\>.postinst debian/\<my_package\>.postinst 
    dpkg-buildpackage -rfakeroot -uc -us

One more question : at the moment I create a full deb with the bdist_deb command and then I repackage it a second time after changing the postinst files. It works but it is still quite inefficient. Do you know a better way to do this with different commands? I can't manage to make it work with debianize.

Thanks again

**Comment by p1otr** [comment]
what's wrong with debianize?

**Comment by ronhanson** [comment]
Well it seems not to be used by bdist_deb or any other command... Once I've
done a debianize and added the postinst files to the Debian folder, I can't
manage to get a packet generated with those postinst through a sdist or
bdist.

**Comment by p1otr** [comment]
$ tar Jcf ./foo_1.2.3.orig.tar.xz foo-1.2.3/
$ cd foo-1.2.3/
$ python setup.py --command-packages=stdeb.command debianize
$ cp ../python*-foo.postinst debian/
$ dpkg-buildpackage # or debuild or (my favourite) sbuild

**Comment by ronhanson** [comment]
Sorry for this dumb question, but I guess I missed something...
What is the file foo_1.2.3.orig.tar.xz ? How do I create it from my
setup.py?
Also, what do you mean in your last line comment with debuild or sbuild?

**Comment by p1otr** [comment]
> > $ tar Jcf ./foo_1.2.3.orig.tar.xz foo-1.2.3/

foo_1.2.3.orig.tar.xz is created with above command
(you can also simply rename tarball generated by sdist)

**Comment by ronhanson** [comment]
Ok, thanks again p1otr.
So, to summarize :

    python setup.py sdist 
    mv dist/foo.tar.gz ../foo.orig.tar.wz
    tar Jcf ./foo_1.2.3.orig.tar.xz foo-1.2.3/
    cd foo-1.2.3/
    python setup.py --command-packages=stdeb.command debianize
    cp ../python*-foo.postinst debian/

Is that alright?

I also have another question now : I want to add custom files to my package, like a cron. So what I'm trying to do is to copy foo.cron file into debian/python3-foo/etc/cron.d/foo and run dpkg-buildpackage again.
But when I do that, the cron files are not included in my package... I could use "data_files"  in setup.py to do so but I'd rather not, as this cron is more of a package/system thing for me, so belongs to the debian packaging.
How can I add files to my package?

Here is a full example script : 

    python3 setup.py sdist #creates dist/foo.tar.gz file
    python3 setup.py --command-packages=stdeb.command sdist_dsc --with-python2=True --with-python3=True --dist-dir=deb_dist --extra-cfg-file=debian.cfg --use-premade-distfile=dist/foo.tar.gz bdist_deb
    cp -Rv my_debian_addons/* deb_dist/*/debian/
    cd deb_dist/* #goes to "deb_dist/foo"
    dpkg-buildpackage -rfakeroot -uc -us
    cd ../..

With my_debian_addons containing the following files: 

    python-foo/etc/cron.d/foo
    python3-foo/etc/cron.d/foo
    python-foo.postinst
    python3-foo.postinst


Thanks in advance!
R.

**Comment by p1otr** [comment]
>     python setup.py sdist 
>     mv dist/foo.tar.gz ../foo.orig.tar.wz
>     tar Jcf ./foo_1.2.3.orig.tar.xz foo-1.2.3/
>     cd foo-1.2.3/
>     python setup.py --command-packages=stdeb.command debianize
>     cp ../python*-foo.postinst debian/

you don't need tar and cd lines

> I also have another question now : I want to add custom files to my
> package, like a cron. So what I'm trying to do is to copy foo.cron
> file into debian/python3-foo/etc/cron.d/foo and run dpkg-buildpackage
> again.

create debian/foo.install file with "contrib/cron/foo /etc/cdon.d/"
inside (see `man dh_install` for details)

That said, I'd generate debian dir *once* and add it to the VCS (but
skip it in MANIFEST) instead of all these workarounds

**Comment by ronhanson** [comment]
Thanks P1otr!
Sorry to bother you but I still have a small issue : 

    /vagrant/deb_dist/foo-0.5.0/debian/python-cc-scraper.install: 1: /vagrant/deb_dist/foo-0.5.0/debian/python-foo.install: contrib/cron/foo: Permission denied
    dh_install: problem reading debian/python-foo.install:
    debian/rules:7: recipe for target 'binary' failed

The .install file contains :

    contrib/cron/foo     etc/cron.d/

If I change the contrib/cron/foo path, it fails saying the file is missing.
Do you have an idea of where I might be wrong?

Thanks again in advance.
R.

**Comment by p1otr** [comment]
if you change contrib/cron/foo, you have to move the file to the new location as well, the first path is source, the second - destination, see manpage for more details

**Comment by ronhanson** [comment]
Hey Piotr,
I can't manage to work around this "Permission denied" problem. The file exists, and whatever I change it yells this error.

Also, I have another small question : when I do a bdist_deb with python3 enabled, it adds all the requirements that it finds in the setup.py file, prefixed with python3-. i.e. it adds python3-configobj. But this package does not exists, only python-configobj. 
The problem is that I have a valid stdeb.cfg, and it still adds those requirements.

How can I set stdeb to only take the dependencies written in stdeb.cfg and not create its own from setup.py?

Thanks again.
R.

**Comment by ronhanson** [comment]
Sorry, my last questions were dumb.
I still have problems with the .install file but I will investigate that more, and will come back in another issue ticket if it still fails.
Anyway, thanks a lot p1otr, you've been great help.

**Comment by ronhanson** [comment]
Well, this permission error only happened in Jessie indeed. It is working like a charm in Ubuntu Trusty for example. Seems like a small dh_install bug I guess.
