### ISSUE TITLE
Misunderstood download URL

### ISSUE THREAD

**Issue by szepeviktor** [astraw/stdeb#127]
```
$ pypi-download llfuse
/usr/local/lib/python3.4/dist-packages/stdeb/downloader.py:127: UserWarning: no md5 digest found -- cannot verify source file
  warnings.warn('no md5 digest found -- cannot verify source file')
OK: downloads
```

https://pypi.python.org/pypi/llfuse/
https://pypi.python.org/pypi?:action=doap&name=llfuse&version=1.1.1

`Download URL: https://bitbucket.org/nikratio/python-llfuse/downloads` (a web page) gets downloaded.
Please advise.

**Comment by szepeviktor** [comment]
It is llfuse's fault?

**Comment by dirk-thomas** [comment]
I will go ahead and close this issue due to its age and inactivity. If you still experience the problem feel free to comment on the ticket and it can be reopened.

**Comment by szepeviktor** [comment]
Okay.
