### ISSUE TITLE
Reenable Travis CI status

### ISSUE THREAD

**Issue by dirk-thomas** [astraw/stdeb#170]
The Travis CI seems to be run for pull requests but the status isn't being reported on the GitHub PR.

@astraw I think this needs your attention since I don't have the necessary permissions to update the settings.

**Comment by astraw** [comment]
Do you know what needs to be done? I looked a bit into the Travis settings UI but I don't see anything relevant, nor do I see a place to add you to the permissions there, which I would be happy to do.

**Comment by dirk-thomas** [comment]
The integration has changed significantly in the past. I would suggest to remove it and then reinstall it and 🤞  😉

**Comment by astraw** [comment]
OK, I deleted the old webhook from travis and signed up for Travis' beta program to automatically migrate the repo to their new integration. Hopefully things Just Work now. I'm closing this but please re-open if it is not actually fixed.

**Comment by dirk-thomas** [comment]
> I deleted the old webhook from travis and signed up for Travis' beta program to automatically migrate the repo to their new integration.

#171 confirms the integration works again. Thank you!
