### ISSUE TITLE
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

### ISSUE THREAD

**Issue by ampledata** [astraw/stdeb#197]
Python 3.12 has removed `SafeConfigParser: https://github.com/python/cpython/blob/d484383861b44b4cf76f31ad6af9a0b413334a89/Doc/whatsnew/3.12.rst#configparser

**Comment by ampledata** [comment]
Dupe of #196

**Comment by luca-della-vedova** [comment]
Hi @ampledata!

Just for another pair of eyes, can you give a spin to the code in the PR since it contains instructions on how to test it and verify whether it solves the issue for you?
