### ISSUE TITLE
Option --setup-env-vars not recognized

### ISSUE THREAD

**Issue by tomduck** [astraw/stdeb#33]
Hi,

I'm trying to compile scipy using stdeb under debian/lenny.  Swig can't find the umfpack header files which are installed under /usr/include/suitesparse.  So, I am trying to pass this path through in the CPATH environment variable using --setup-env-vars.  I'm not sure that would work, but in any case I get an error message that was unexpected: 

distutils.errors.DistutilsArgError: option --setup-env-vars not recognized.

The full session is copied below.

Thanks,
Tom
## 

$ py2dsc --force-buildsystem=False --setup-env-vars scipy-0.7.2.tar.gz

Traceback (most recent call last):
  File "/usr/bin/py2dsc", line 157, in <module>
    main()
  File "/usr/bin/py2dsc", line 154, in main
    sys.exit(runit())
  File "/usr/bin/py2dsc", line 29, in runit
    args = parser.getopt(object=optobj)
  File "/usr/lib/python2.5/distutils/fancy_getopt.py", line 260, in getopt
    raise DistutilsArgError, msg
distutils.errors.DistutilsArgError: option --setup-env-vars not recognized

**Comment by dirk-thomas** [comment]
Closing due to age and inactivitiy. Please feel free to comment if this is still a problem and the ticket can be reopened.
