### ISSUE TITLE
option --stdeb-patch-file not recognized

### ISSUE THREAD

**Issue by tomduck** [astraw/stdeb#34]
Hi,

This is probably related to a similar issue I reported earlier today, using stdeb 0.6.0 under debian/lenny.  The --stdeb-patch-file option is reported as unrecognized.  The full session is reported below.

Cheers,
Tom
## 

$ py2dsc --force-buildsystem=False --stdeb-patch-file=scipy-0.7.2.diff scipy-0.7.2.tar.gz

Traceback (most recent call last):
  File "/usr/bin/py2dsc", line 157, in <module>
    main()
  File "/usr/bin/py2dsc", line 154, in main
    sys.exit(runit())
  File "/usr/bin/py2dsc", line 29, in runit
    args = parser.getopt(object=optobj)
  File "/usr/lib/python2.5/distutils/fancy_getopt.py", line 260, in getopt
    raise DistutilsArgError, msg
distutils.errors.DistutilsArgError: option --stdeb-patch-file not recognized

**Comment by dirk-thomas** [comment]
Closing due to age and inactivitiy. Please feel free to comment if this is still a problem and the ticket can be reopened.
