### ISSUE TITLE
don't build-depend on python-all-dev when only building for a certain Python version

### ISSUE THREAD

**Issue by astraw** [astraw/stdeb#35]
[As reported by lukshintim on the distutils mailing list](http://mail.python.org/pipermail/distutils-sig/2010-July/016452.html), when changing the XS-Python-Version option in stdeb.cfg, the Build-Depends in debian/control should reflect that. Currently they are fixed to python-all-dev.

**Comment by dirk-thomas** [comment]
Since 0ebcd074c8ebeb56702002fb27594c39fbd36a48 Python 3 packages depend on `python3-all-dev`. Assuming that is sufficient I will go ahead and close this.

Please feel free to comment and clarify in which cases this is still a problem and the ticket can be reopened.
