### ISSUE TITLE
Empty string as data_files first parameter generates errors.

### ISSUE THREAD

**Issue by quasipedia** [astraw/stdeb#45]
In my setup.py:

```
py_modules = ['src/prog'],
data_files=['', ['src/data.yml']],
```

The setup.py script that I wrote works fine with

```
python setup.py sdist
```

(the tar.gz that is being generated has both my module and data file in
the same directory) but it throws errors when I run:

```
python setup.py --command-packages=stdeb.command bdist_deb
```

specifically it says:

```
warning: install_data: setup script did not provide a directory for '' -- installing right in
'/home/<mydirectory>/debian/python-<myapplicationname>/usr'
error: can't copy '': doesn't exist or not a regular file
```

so I believe stdeb is simply unable to understand that the empty string
means "put the data file together with the module", the way the regular
distutils can.

Am I right or did I misunderstand anything?

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.
