### ISSUE TITLE
stdeb seems to be adding too many Python dependencies

### ISSUE THREAD

**Issue by bmhatfield** [astraw/stdeb#49]
Built on a recent Ubuntu, stdeb is adding a false dependency on Python 2.7 to a build I am running, even when I override it via XS-Python-Version:

Depends: python2.7 | python2.6, python (>= 2.7.1-0ubuntu2), python (<< 2.8)

How do I tell stdeb not to include the system version of Python as a dependency?

**Comment by dirk-thomas** [comment]
Closing due to age.

Please feel free to comment if this is still a problem and the ticket can be reopened.
