### ISSUE TITLE
what is the motivation for breaking virtualenv behavior?

### ISSUE THREAD

**Issue by kzw** [astraw/stdeb#91]
https://github.com/astraw/stdeb/blob/master/stdeb/util.py#L1010

I went out of my way to run setup.py with virtualenv python interpreter because I want my debian package to install my app to a virtualenv.

If people want to install to system wide python folders, they would know not to use virtualenv python to run setup.py.

Also there may be other systems where sys.prefix is not /usr even for system wide python.

Please seriously reconsider this decision.  I am going to maintain locally patched copy until then.

**Comment by astraw** [comment]
I understand your reasoning, but in this case why not just use a pip requirements.txt file?

**Comment by kzw** [comment]
I do not understand your comment.  Are you saying that when I use vitualenv I should not bother with Debian packaging?  For the same reasons when not bothering with virtualenv.  For example we do not want to install build dependencies in production

**Comment by astraw** [comment]
Typically (always?) .deb packages install stuff system wide. Using a .deb package to install into a particular user account is... atypical. [Anaconda (or just conda)](https://store.continuum.io/cshop/anaconda/), for example, would let you install pre-built packages into user accounts, as would [wheels](https://pypi.python.org/pypi/wheel), I think. Alternatively, could you use system installed packages build with stdeb and then use e.g. docker containers to run multiple such systems on a single physical computer?

**Comment by kzw** [comment]
0. Sorry for the confusion about 'system wide' terminology.  virtualenv does not have to be for a user who is going to ssh into the system and use the software manually there.  In our case, it is going to be for many production web applications.

1. You can search on google on why people do this.  Search for 'spotify', 'dh-virtualenv', and links there in.  And they are not using stdeb.  I would like to continue using stdeb which is currently only good if you want to have sys.prefix ='/usr'

2. When software companies distribute python/ruby applications etc they often choose to package it with their own python/ruby interpreters for many good reasons.   This way they have complete control over their software and not have to worry about dependencies hell.

**Comment by astraw** [comment]
This code has prevented me from shooting myself in the foot several times. (I often do development in a virtualenv but peronally do not ever want to build a .deb that will install into that virtualenv.) However, I'm quite careful now about whether I'm in a virtualenv or not and thus would be OK with removing this check.

All that said, I think conda and wheels both aim to directly solve your use case whereas I think it will always be atypical to use .debs as a distribution mechanism.
