### ISSUE TITLE
Wrong prefix when creating a deb from a venv

### ISSUE THREAD

**Issue by dguerri** [astraw/stdeb#95]
Hi,
the following change

  https://github.com/astraw/stdeb/pull/92/files#diff-851fffd0ddbf27ef6a8870848be10390L1010

seems to have broken the creation of a deb package meant for the "system environment" when using stdeb in a venv.

Is there a way to explicitly configure that prefix?

**Comment by astraw** [comment]
The discussion about this was at #91. Apparently some people do want to make .deb files that install into a virtualenv. I personally don't care much and I can see arguments either way.

Do I understand you correctly that some kind of `--force-FHS-standard` option that forces `--prefix=/usr`  be OK for you?

**Comment by dguerri** [comment]
Hi Astraw, sorry for the duplicate issue.
Something like `--force-FHS-standard` would be great. I think it would be even better to make that prefix configurable via std.cfg or CLI parameter

**Comment by dguerri** [comment]
@astraw: it is not clear to me what you mean with "Apparently some people do want to make .deb files that install into a virtualenv".

I have some packaging jobs that create deb from source repositories. As these jobs are running on a shared jenkins node, I had to use a venv to install stdeb and its dependencies.
So, when I run stdeb from within that venv, it created deb packages with a wrong prefix (i.e. the path to the venv on the jenkins node).

**Comment by paternal** [comment]
To illustrate what @dguerri is saying, here is the list of files installed by a package created with `stdeb`. The first few lines are correct (some files installed in `/usr`), but the following files are installed in my home directory `/home/louis/…`, which is weird (as [you already pointed out](91#issuecomment-69005272)).

I do not fully undersand what @kzw  means, but would not #94 solve both this issue and #91 ?

~~~
$ dpkg -L python3-scal
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python3-scal
/usr/share/doc/python3-scal/copyright
/usr/share/doc/python3-scal/changelog.Debian.gz
/usr/share/doc/python3-scal/changelog.gz
/home
/home/louis
/home/louis/projets
/home/louis/projets/scal
/home/louis/projets/scal/virtualenv
/home/louis/projets/scal/virtualenv/bin
/home/louis/projets/scal/virtualenv/bin/scal
/home/louis/projets/scal/virtualenv/lib
/home/louis/projets/scal/virtualenv/lib/python3
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/template.py
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/options.py
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/__init__.py
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/errors.py
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/data
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/data/templates
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/data/templates/template.tex
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/main.py
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/scal/calendar.py
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info/zip-safe
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info/entry_points.txt
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info/dependency_links.txt
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info/requires.txt
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info/top_level.txt
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info/PKG-INFO
/home/louis/projets/scal/virtualenv/lib/python3/dist-packages/Scal-0.2.0.egg-info/SOURCES.txt
~~~

**Comment by astraw** [comment]
@paternal yes, this is completely expected given #91 and #92. But given you and @dguerri have brought this up and it is a change of behavior with 0.8.4 released 2 days ago, I'm tempted to quickly make a new release that reverts to the old behavior -- I did not realize how relied-upon the original behavior is.

I could add an option like --use-sys-prefix to allow installing into a virtualenv if desired. @kzw - would that work for you?

**Comment by paternal** [comment]
> I could add an option like --use-sys-prefix to allow installing into a virtualenv if desired. @kzw - would that work for you?

Yes, but I would say that for backward compatibility reasons, using `/usr` as the prefix should be the default, and the virtualenv prefix should be on option. Making virtualenv the default may be changed in a version `1.0` (or at least `0.9`), as, as we reported, we expected this not to change (and we may not be the only ones).

Maybe an option `--prefix={sys,virtualenv}` (defaulting to `sys` right now)? Or `--use-prefix={sys,virtualenv}` (since the `--prefix` option usually takes a path in argument in tools like `make` or `configure`)? And a option `prefix` in the configuration file?

**Comment by dguerri** [comment]
+1 to @paternal proposal about the default value
Thanks @astraw for fixing this issue.

**Comment by astraw** [comment]
@paternal your comment makes me realize my proposal had a misleading name. By `--use-sys-prefix` I meant `"--prefix=%s"%sys.prefix` (not `"--prefix=/usr"`). But I can see how the name is misleading. So a better name would be `--allow-virtualenv-install-location`. I think that should allow @kzw's use case and just have a slight break in compatibility until I can push out a new release.

Sorry about the trouble. Like I said, I didn't realize that people were relying on this behavior.

**Comment by dguerri** [comment]
Brilliant, thanks.

**Comment by paternal** [comment]
Thanks!

**Comment by jul** [comment]
sorry for understesting my patch
