### ISSUE TITLE
Signing support?

### ISSUE THREAD

**Issue by Tinche** [astraw/stdeb#96]
As far as I can tell, stdeb can't sign produced source packages? It'd be useful if it could, so I could upload them to PPAs without further hassle.

**Comment by Tinche** [comment]
Cool, thanks!

**Comment by bkmeneguello** [comment]
Is this actually working?

**Comment by mikepurvis** [comment]
It is, but it's not in the 0.8.5 release, so you have to install from source to use it— I was a bit confused too. :)
